variables:
  #Variables for dev deploy stage
  # DEV_SSH_HOST: <gitlab_variables>
  # DEV_SSH_USER: <gitlab_variables>
  # DEV_SSH_PASS: <gitlab_variables>
  # DEV_DIR_ROOT: <gitlab_variables>

  #Variables for production deploy stage
  # PROD_SSH_HOST: <gitlab_variables>
  # PROD_SSH_USER: <gitlab_variables>
  # PROD_SSH_PASS: <gitlab_variables>
  # PROD_DIR_ROOT: <gitlab_variables>

stages: 
  - build
  - deploy

build-prod-stage:
  image: node:6
  stage: build
  only:
    - master
  script:
    - npm install --progress=false
    - mkdir public_html
    - sed -i "s/..\/public_html/public_html/g" config/index.js
    - npm run build
  artifacts:
    expire_in: 1 hrs
    paths:
      - public_html
      
build-dev-stage:
  image: node:6
  stage: build
  only:
    - development
  script:
    - npm install --progress=false
    - mkdir public_html
    - sed -i "s/..\/public_html/public_html/g" config/index.js
    - sed -i "/HOST_URL/c\HOST_URL:\'\"http:\/\/dev.sekampus.id\"\'" config/prod.env.js
    - npm run build
  artifacts:
    expire_in: 1 hrs
    paths:
      - public_html

deploy-dev-stage:
  image: alpine
  stage: deploy
  only:
    - development
  script:
    - apk add --no-cache rsync openssh sshpass
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - sshpass -p $DEV_SSH_PASS rsync -rav --delete public_html/ $DEV_SSH_USER@$DEV_SSH_HOST:$DEV_DIR_ROOT

deploy-prod-stage:
  image: alpine
  stage: deploy
  only:
    - master
  script:
    - apk add --no-cache rsync openssh sshpass
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - sshpass -p $PROD_SSH_PASS rsync -rav --delete public_html/ $PROD_SSH_USER@$PROD_SSH_HOST:$PROD_DIR_ROOT